# Generated by Django 2.2.1 on 2019-06-02 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_executor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_active',
        ),
    ]
